import React from 'react'

import Layout from '../components/layout'

const IndexPage = () => (
  <Layout>
    <h1>Introduction</h1>
    <p>This is an example React site generated by gatsby.</p>
  </Layout>
)

export default IndexPage
